// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSelf() {
  return window['go']['main']['App']['GetSelf']();
}

export function OpenDownloadsFolder() {
  return window['go']['main']['App']['OpenDownloadsFolder']();
}

export function SendPaths(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPaths'](arg1, arg2, arg3);
}

export function SendSnippet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendSnippet'](arg1, arg2, arg3, arg4);
}
