// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetSelf():Promise<backend.Peer>;

export function OpenDownloadsFolder():Promise<void>;

export function SendPaths(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function SendSnippet(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;
